# Hand-labelled query set over tests/fixtures/repo_v1 (36 chunks, 13 files).
# Labels written by reading every line of the fixture source; binary relevance.
# Keys are "<file_path>:<start_line>", which is stable across both index builds.
QUERIES = {
"HQ01": ("how is the input preprocessed before going to the main function",
         {"src/utils/normalize.js:33","src/main.js:7","src/utils/normalize.js:24","src/utils/normalize.js:12"}),
"HQ02": ("which function calls preprocessInput before resolveTool",
         {"src/tools/registry.js:8"}),
"HQ03": ("where is the bluetooth settings deeplink constant used",
         {"src/agents/bluetooth.js:1","src/agents/bluetooth.js:28"}),
"HQ04": ("strip control characters and collapse repeated whitespace in a raw payload",
         {"src/utils/normalize.js:12"}),
"HQ05": ("lower-case and unicode-normalise text so token matching is stable",
         {"src/utils/normalize.js:24"}),
"HQ06": ("what is the default request timeout in milliseconds",
         {"src/constants.js:1"}),
"HQ07": ("how is the maximum retry count defined",
         {"src/constants.js:1"}),
"HQ08": ("look a tool up by its normalised name in the table",
         {"src/tools/registry.js:20"}),
"HQ09": ("build the lookup table lazily with a nested closure per entry",
         {"src/tools/registry.js:28","src/tools/registry.js:31"}),
"HQ10": ("drop the memoised table so the next call rebuilds it",
         {"src/tools/registry.js:44"}),
"HQ11": ("resolve a raw deeplink string into a routable target",
         {"src/agents/bluetooth.js:17"}),
"HQ12": ("forget any cached routing decision",
         {"src/agents/bluetooth.js:48"}),
"HQ13": ("report whether the agent can service a deeplink at all",
         {"src/agents/bluetooth.js:40"}),
"HQ14": ("remove duplicate items from a list while preserving order",
         {"src/dup/copy_a.js:6","src/dup/copy_b.js:6"}),
"HQ15": ("two modules that require each other in a circular import",
         {"src/circular/a.js:1","src/circular/b.js:1","src/circular/a.js:3","src/circular/b.js:3"}),
"HQ16": ("deeply nested closures that return a function at every level",
         {"src/deep/nested.js:5","src/deep/nested.js:6","src/deep/nested.js:7",
          "src/deep/nested.js:8","src/deep/nested.js:9","src/deep/nested.js:10"}),
"HQ17": ("french accented label text containing an emoji",
         {"src/i18n/labels.js:5"}),
"HQ18": ("truncate the normalised payload at a four kilobyte limit",
         {"src/utils/normalize.js:33"}),
"HQ19": ("entry point that processes one inbound request end to end",
         {"src/main.js:7"}),
"HQ20": ("which url schemes are supported",
         {"src/constants.js:1"}),
}
